/**
 * Real Estate pack — property search, property detail, mortgage simulator,
 * virtual tour, agent contact.
 *
 * Maturity: MATURE. Conventions are quite consistent across the major
 * portals (Zillow, Redfin, SeLoger, Idealista, ImmoScout24, Idealista).
 * Some locale-specific vocabulary (especially around mortgage / financing).
 */

import { JourneyBlueprint } from '../../../types';

const REALESTATE_PROPERTY_SEARCH: JourneyBlueprint = {
  id: 'realestate.property-search',
  name: 'Recherche immobiliere et decouverte de bien',
  description:
    "Accompagne un acheteur ou locataire potentiel: lancer une recherche, ouvrir la fiche d'un bien, simuler un pret puis contacter l'agent.",
  vertical: 'realestate',
  intent: 'primary-action',
  minResolvedSteps: 2,
  priority: 10,
  steps: [
    {
      semanticRole: 'realestate.property-search',
      title: 'Lancez votre recherche',
      description:
        "Saisissez votre zone et vos criteres (budget, surface, nombre de pieces). Les annonces correspondantes apparaissent sur la carte.",
      position: 'BOTTOM',
      action: 'CLICK',
      required: true,
      targetHints: {
        routePatterns: [
          '/search', '/properties', '/listings', '/rent', '/buy',
          '/recherche', '/annonces', '/biens', '/location', '/achat',
          '/buscar', '/inmuebles', '/anuncios', '/alquiler', '/comprar',
          '/suche', '/immobilien', '/mieten', '/kaufen',
          '/ricerca', '/immobili', '/affitto', '/vendita',
          '/buscar', '/imoveis', '/anuncios', '/alugar', '/comprar',
        ],
        selectorHints: [
          '[data-tour-id="property-search"]',
          '[data-tour-id="search-properties"]',
          '[data-tour-id*="search-form"]',
          '[data-tour-id*="property-search"]',
          'form[class*="search-form"]',
          'form[class*="SearchForm"]',
          'form[class*="PropertySearch"]',
          'input[type="search"][placeholder*="city" i]',
          'input[type="search"][placeholder*="ville" i]',
          'input[type="search"][placeholder*="ciudad" i]',
          'input[type="search"][placeholder*="stadt" i]',
          'input[name*="location"]',
          'input[name*="city"]',
          'a[href*="/search"]',
          'a[href*="/recherche"]',
          'a[href*="/buscar"]',
        ],
        semanticTokens: [
          'search', 'find property', 'find a home',
          'recherche', 'chercher un bien', 'trouver un logement',
          'busqueda', 'buscar inmueble', 'encontrar vivienda',
          'suche', 'immobilie suchen', 'wohnung finden',
          'ricerca', 'cerca immobile', 'trovare casa',
          'busca', 'buscar imovel', 'encontrar casa',
        ],
        actionVerbs: [
          'search', 'find homes', 'browse properties',
          'rechercher', 'trouver un bien',
          'buscar', 'encontrar inmueble',
          'suchen', 'immobilie finden',
          'cerca', 'trovare immobile',
          'buscar', 'encontrar imovel',
        ],
        elementTags: ['form', 'button', 'input', 'a'],
      },
    },
    {
      semanticRole: 'realestate.property-detail',
      title: 'Consultez la fiche du bien',
      description:
        "La fiche detaillee presente les photos, le descriptif, le DPE, l'historique du prix et la localisation. Tout ce qu'il faut pour se projeter.",
      position: 'BOTTOM',
      action: 'CLICK',
      inferAfter: ['realestate.property-search'],
      targetHints: {
        routePatterns: [
          '/property/', '/listing/', '/home/',
          '/bien/', '/annonce/', '/logement/',
          '/inmueble/', '/anuncio/',
          '/immobilie/', '/wohnung/', '/objekt/',
          '/immobile/', '/annuncio/',
          '/imovel/', '/anuncio/',
        ],
        selectorHints: [
          '[data-tour-id="property-detail"]',
          '[data-tour-id="property-card"]',
          '[data-tour-id*="property"]',
          '[data-tour-id*="listing"]',
          'article[class*="property-card"]',
          'article[class*="PropertyCard"]',
          'article[class*="ListingCard"]',
          'a[href*="/property/"]',
          'a[href*="/listing/"]',
          'a[href*="/bien/"]',
          'a[href*="/annonce/"]',
          'a[href*="/inmueble/"]',
          'a[href*="/immobilie/"]',
          'a[href*="/immobile/"]',
          'a[href*="/imovel/"]',
        ],
        semanticTokens: [
          'property', 'listing', 'home', 'apartment', 'house',
          'bien', 'annonce', 'logement', 'appartement', 'maison',
          'inmueble', 'anuncio', 'vivienda', 'apartamento', 'casa',
          'immobilie', 'objekt', 'wohnung', 'haus',
          'immobile', 'annuncio', 'appartamento', 'casa',
          'imovel', 'anuncio', 'apartamento', 'casa',
        ],
        elementTags: ['a', 'button'],
      },
    },
    {
      semanticRole: 'realestate.mortgage-simulator',
      title: 'Simulez votre financement',
      description:
        "Le simulateur de pret estime mensualites et frais selon votre apport et la duree souhaitee. Indispensable avant de visiter.",
      position: 'RIGHT',
      action: 'CLICK',
      targetHints: {
        routePatterns: [
          '/mortgage', '/loan-calculator', '/financing',
          '/credit', '/simulation-pret', '/simulateur',
          '/hipoteca', '/simulador-hipoteca', '/financiacion',
          '/hypothek', '/finanzierung', '/baufinanzierung',
          '/mutuo', '/simulatore-mutuo',
          '/financiamento', '/simulador',
        ],
        selectorHints: [
          '[data-tour-id="mortgage-simulator"]',
          '[data-tour-id="loan-calculator"]',
          '[data-tour-id*="mortgage"]',
          '[data-tour-id*="loan"]',
          '[data-tour-id*="financing"]',
          'a[href*="/mortgage"]',
          'a[href*="/loan"]',
          'a[href*="/credit"]',
          'a[href*="/simulation"]',
          'a[href*="/hipoteca"]',
          'a[href*="/hypothek"]',
          'a[href*="/mutuo"]',
          'a[href*="/financiamento"]',
          'form[class*="mortgage"]',
          'form[class*="MortgageCalculator"]',
        ],
        semanticTokens: [
          'mortgage', 'loan', 'financing', 'calculator',
          'pret', 'credit', 'financement', 'simulation',
          'hipoteca', 'prestamo', 'financiacion',
          'hypothek', 'darlehen', 'finanzierung',
          'mutuo', 'prestito', 'finanziamento',
          'hipoteca', 'emprestimo', 'financiamento',
        ],
        actionVerbs: [
          'calculate mortgage', 'simulate loan',
          'simuler un pret', 'calculer mon credit',
          'simular hipoteca', 'calcular prestamo',
          'hypothek berechnen',
          'simula mutuo', 'calcola mutuo',
          'simular financiamento',
        ],
        elementTags: ['a', 'button', 'form'],
      },
    },
    {
      semanticRole: 'realestate.virtual-tour',
      title: 'Faites la visite virtuelle',
      description:
        "La visite virtuelle vous permet de parcourir chaque piece a 360 degres avant de vous deplacer. Gain de temps considerable.",
      position: 'TOP',
      action: 'CLICK',
      targetHints: {
        selectorHints: [
          '[data-tour-id="virtual-tour"]',
          '[data-tour-id="360-tour"]',
          '[data-tour-id*="virtual-tour"]',
          '[data-tour-id*="360"]',
          'button[class*="virtual-tour"]',
          'button[class*="VirtualTour"]',
          'button[class*="360"]',
          'iframe[src*="virtual-tour"]',
          'iframe[src*="matterport"]',
          'iframe[src*="360"]',
          'a[href*="virtual-tour"]',
          'button[aria-label*="virtual tour" i]',
          'button[aria-label*="360" i]',
          'button[aria-label*="visite virtuelle" i]',
        ],
        semanticTokens: [
          'virtual tour', '360 tour', 'walk-through',
          'visite virtuelle', '360', 'visite immersive',
          'tour virtual', '360',
          'virtuelle besichtigung', '360 rundgang',
          'tour virtuale', '360',
          'tour virtual', '360',
        ],
        actionVerbs: [
          'view virtual tour', 'start 360 tour',
          'lancer la visite virtuelle',
          'iniciar tour virtual',
          'virtuelle tour starten',
          'avvia tour virtuale',
          'iniciar tour virtual',
        ],
        elementTags: ['a', 'button'],
      },
    },
    {
      semanticRole: 'realestate.contact-agent',
      title: 'Contactez l agent',
      description:
        "Pour une visite physique ou une question, joignez l'agent du bien. Le formulaire transmet votre message directement.",
      position: 'BOTTOM',
      action: 'CLICK',
      targetHints: {
        selectorHints: [
          '[data-tour-id="contact-agent"]',
          '[data-tour-id="agent-contact"]',
          '[data-tour-id*="contact-agent"]',
          'button[class*="contact-agent"]',
          'button[class*="ContactAgent"]',
          'button[class*="AgentContact"]',
          'a[class*="contact-agent"]',
          'form[aria-label*="contact agent" i]',
          'button[aria-label*="contact agent" i]',
          'button[aria-label*="contacter agent" i]',
        ],
        semanticTokens: [
          'contact agent', 'message agent', 'book viewing',
          'contacter agent', 'demander visite',
          'contactar agente', 'pedir visita',
          'agent kontaktieren', 'besichtigung anfragen',
          'contatta agente', 'richiedi visita',
          'contatar agente', 'agendar visita',
        ],
        actionVerbs: [
          'contact agent', 'request viewing', 'book viewing',
          'contacter agent', 'demander une visite',
          'contactar agente',
          'agent kontaktieren',
          'contatta agente',
          'contatar agente',
        ],
        elementTags: ['button', 'a', 'form'],
      },
    },
  ],
};

export const realestateBlueprints: JourneyBlueprint[] = [REALESTATE_PROPERTY_SEARCH];
